github actions unit tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,14 +28,14 @@ jobs:
       - name: Run unit tests
         run: yarn test:ci
 
-      - name: Upload unit test results
-        uses: dorny/test-reporter@v1
-        # run this step even if previous step failed
-        if: success() || failure()
-        with:
-          name: unit-test-results
-          path: reports/unit-tests/*.xml
-          reporter: jest-junit
+      # - name: Upload unit test results
+      #   uses: dorny/test-reporter@v1
+      #   # run this step even if previous step failed
+      #   if: success() || failure()
+      #   with:
+      #     name: unit-test-results
+      #     path: reports/unit-tests/*.xml
+      #     reporter: jest-junit
 
       - name: Build
         run: yarn build
